/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2022-12-19 05:55:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/include/top.jspf", Long.valueOf(1671088965000L));
    _jspx_dependants.put("/include/bottom.jspf", Long.valueOf(1670490642000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1670464208072L));
    _jspx_dependants.put("jar:file:/Users/poby/StudySpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webSpringTest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/js_css/style.css\" type=\"text/css\">\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"topMenu\">\n");
      out.write("		<ul>\n");
      out.write("			<li><a href=\"/myapp/\">홈</a></li>\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			<li><a href=\"/myapp/board/boardList\">게시판</a></li>\n");
      out.write("			<li><a href=\"/myapp/data/dataList\">자료실</a></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	$(function(){\n");
      out.write("		// 아이디 중복확인 버튼 누르면\n");
      out.write("		$(\"#idCheck\").click(function(){\n");
      out.write("			if($(\"#username\").val()!=\"\"){\n");
      out.write("				window.open(\"/myapp/member/idCheck?username=\"+$(\"#username\").val(),\"idCheck\",\"width=500px, height=400px\");\n");
      out.write("			}else{\n");
      out.write("				alert(\"아이디를 입력해주세요.\")\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		// 아이디 입력칸에 입력되면\n");
      out.write("		$(\"#username\").keyup(function(){\n");
      out.write("			$(\"#idCheckStatus\").val(\"N\");\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		// 우편번호 찾기 버튼 누르면\n");
      out.write("		$(\"#searchZipcode\").click(function(){\n");
      out.write("			// 우편번호 검색 팝업창 생성\n");
      out.write("			window.open(\"/myapp/member/searchZipcode\",\"zipcode\",\"width=600px, height=500px, top=200px, left=200px\");\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		// 회원가입 유효성 검사\n");
      out.write("		$(\"#signupForm\").submit(function(){\n");
      out.write("			// 아이디 조건\n");
      out.write("			// 영어, 숫자, '_'로 이루어진 길이 6~15자리\n");
      out.write("			\n");
      out.write("			// 정규표현식\n");
      out.write("			// ^ : 처음부터 문자를 검색,	$ : 끝까지 검색\n");
      out.write("			var reg = /^[A-Za-z]{1}\\w{5,14}$/	// \\w : 영대소문자,숫자,_	\n");
      out.write("			if(!reg.test($(\"#username\").val())){	// 맞으면 true, 틀리면 false\n");
      out.write("				alert(\"아이디를 잘못 입력하였습니다.\\n아이디는 6~15자리의 영문자, 숫자, _만 사용할 수 있습니다.\");\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			// 비밀번호 확인\n");
      out.write("			if($(\"#password\").val() != $(\"#v-password\").val()){\n");
      out.write("				alert(\"비밀번호를 확인하세요.\");\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			// 이름 조건 : 한글로 2~7글자까지 허용\n");
      out.write("			reg = /^[가-힣]{2,7}$/\n");
      out.write("			if(!reg.test($(\"#name\").val())){\n");
      out.write("				alert(\"이름은 한글 2~7자까지 허용합니다.\");\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			// 연락처 검사\n");
      out.write("			var tel = $(\"#tel1\").val()+\"-\"+$(\"#tel2\").val()+\"-\"+$(\"#tel3\").val();\n");
      out.write("			console.log(\"tel -> \", tel);	// 브라우저 콘솔에 전화번호 표시\n");
      out.write("			// 지역번호 : 010, 02, 031, 032, 041, 042\n");
      out.write("			reg = /^(010|02|031|032|041|042)-[0-9]{3,4}-[0-9]{4}$/\n");
      out.write("			if(!reg.test(tel)){\n");
      out.write("				alert(\"전화번호를 확인하세요.\");\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			// 이메일 검사\n");
      out.write("			// smg1024@naver.com	smg1024@cau.ac.kr\n");
      out.write("			if($(\"#email\").val()!=\"\"){	// 이메일은 필수 입력 항목이 아님\n");
      out.write("				// 이메일은 다른 사이트의 이메일을 가져오는 것이기 때문에 최대한 널널한 조건으로 설정\n");
      out.write("				// ? : 있거나 없거나\n");
      out.write("				reg = /^\\w{6,15}[@][a-z0-9]{2,8}[.][a-z]{1,3}([.][a-z]{1,3})?$/\n");
      out.write("				if(!reg.test($(\"#email\").val())){\n");
      out.write("					alert(\"잘못된 이메일 주소입니다.\");\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			// 아이디 중복확인 검사\n");
      out.write("			if($(\"#idCheckStatus\").val()==\"N\"){\n");
      out.write("				alert(\"아이디 중복 확인하세요.\");\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<title>회원가입</title>\n");
      out.write("<div class=\"container\">\n");
      out.write("	<h1>회원가입 Form</h1>\n");
      out.write("	<form method=\"post\" action=\"/myapp/member/signupOk\" id=\"signupForm\">\n");
      out.write("		<ul>\n");
      out.write("			<li>아이디</li>\n");
      out.write("			<li>\n");
      out.write("				<input type=\"text\" name=\"username\" id=\"username\">\n");
      out.write("				<input type=\"button\" value=\"중복확인\" id=\"idCheck\">\n");
      out.write("				<input type=\"hidden\" value=\"N\" id=\"idCheckStatus\">\n");
      out.write("			</li>\n");
      out.write("			<li>비밀번호</li>\n");
      out.write("			<li><input type=\"password\" name=\"password\" id=\"password\"></li>\n");
      out.write("			<li>비밀번호 확인</li>\n");
      out.write("			<li><input type=\"password\" name=\"v-password\" id=\"v-password\"></li>\n");
      out.write("			<li>이름</li>\n");
      out.write("			<li><input type=\"text\" name=\"name\" id=\"name\"></li>\n");
      out.write("			<li>연락처</li>\n");
      out.write("			<li>\n");
      out.write("				<input type=\"text\" name=\"tel1\" id=\"tel1\">-\n");
      out.write("				<input type=\"text\" name=\"tel2\" id=\"tel2\">-\n");
      out.write("				<input type=\"text\" name=\"tel3\" id=\"tel3\">\n");
      out.write("			</li>\n");
      out.write("			<li>이메일</li>\n");
      out.write("			<li><input type=\"text\" name=\"email\" id=\"email\"></li>\n");
      out.write("			<li>우편번호</li>\n");
      out.write("			<li>\n");
      out.write("				<input type=\"text\" name=\"zipcode\" id=\"zipcode\" readonly>\n");
      out.write("				<input type=\"button\" value=\"우편번호 찾기\" id=\"searchZipcode\">\n");
      out.write("			</li>\n");
      out.write("			<li>주소</li>\n");
      out.write("			<li><input type=\"text\" name=\"addr\" id=\"addr\" style=\"width:50%\"></li>\n");
      out.write("			<li>상세주소</li>\n");
      out.write("			<li><input type=\"text\" name=\"detailaddr\" id=\"detailaddr\"></li>\n");
      out.write("			<li><input type=\"submit\" value=\"회원가입\"></li>\n");
      out.write("		</ul>\n");
      out.write("	</form>\n");
      out.write("</div>");
      out.write("\n");
      out.write("	<div class=\"bottomMenu\">\n");
      out.write("		@copyright Poby.\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /include/top.jspf(15,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ logStatus!='Y' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<li><a href=\"/myapp/member/login\">로그인</a></li>\n");
          out.write("				<li><a href=\"/myapp/member/signup\">회원가입</a></li>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /include/top.jspf(19,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ logStatus=='Y' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<li><a href=\"/myapp/member/logout\">로그아웃</a></li>\n");
          out.write("				<li><a href=\"/myapp/member/myAccount?username=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ logUsername }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ logName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">회원정보수정</a></li>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
