/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2022-12-10 14:31:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/include/top.jspf", Long.valueOf(1670559462000L));
    _jspx_dependants.put("/include/bottom.jspf", Long.valueOf(1670490642000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1670464208072L));
    _jspx_dependants.put("jar:file:/Users/poby/StudySpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webSpringTest/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/js_css/style.css\" type=\"text/css\">\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"topMenu\">\n");
      out.write("		<ul>\n");
      out.write("			<li><a href=\"#\">홈</a></li>\n");
      out.write("			<li><a href=\"#\">로그인</a><a href=\"/myapp/member/signup\">회원가입</a></li>\n");
      out.write("			<li><a href=\"#\">로그아웃/회원정보수정</a></li>\n");
      out.write("			<li><a href=\"#\">게시판</a></li>\n");
      out.write("			<li><a href=\"#\">자료실</a></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	$(function(){\n");
      out.write("		$(\"#idCheck\").click(function(){\n");
      out.write("			if($(\"#username\").val()!=\"\"){\n");
      out.write("				window.open(\"/myapp/member/idCheck?username=\"+$(\"#username\").val(),\"idCheck\",\"width=500px, height=400px\");\n");
      out.write("			}else{\n");
      out.write("				alert(\"아이디를 입력해주세요.\")\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#username\").keyup(function(){\n");
      out.write("			$(\"#idCheckStatus\").val(\"N\");\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<title>회원가입</title>\n");
      out.write("<div class=\"container\">\n");
      out.write("	<h1>회원가입 Form</h1>\n");
      out.write("	<form method=\"post\" action=\"/myapp/member/signup\">\n");
      out.write("		<ul>\n");
      out.write("			<li>아이디</li>\n");
      out.write("			<li>\n");
      out.write("				<input type=\"text\" name=\"username\" id=\"username\">\n");
      out.write("				<input type=\"button\" value=\"중복확인\" id=\"idCheck\">\n");
      out.write("				<input type=\"hidden\" value=\"N\" id=\"idCheckStatus\">\n");
      out.write("			</li>\n");
      out.write("			<li>비밀번호</li>\n");
      out.write("			<li><input type=\"password\" name=\"password\" id=\"password\"></li>\n");
      out.write("			<li>비밀번호 확인</li>\n");
      out.write("			<li><input type=\"password\" name=\"v-password\" id=\"v-password\"></li>\n");
      out.write("			<li>이름</li>\n");
      out.write("			<li><input type=\"text\" name=\"name\" id=\"name\"></li>\n");
      out.write("			<li>연락처</li>\n");
      out.write("			<li>\n");
      out.write("				<input type=\"text\" name=\"tel1\" id=\"tel1\">-\n");
      out.write("				<input type=\"text\" name=\"tel2\" id=\"tel2\">-\n");
      out.write("				<input type=\"text\" name=\"tel3\" id=\"tel3\">\n");
      out.write("			</li>\n");
      out.write("			<li>이메일</li>\n");
      out.write("			<li><input type=\"text\" name=\"email\" id=\"email\"></li>\n");
      out.write("			<li>우편번호</li>\n");
      out.write("			<li>\n");
      out.write("				<input type=\"text\" name=\"zipcode\" id=\"zipcode\">\n");
      out.write("				<input type=\"button\" value=\"우편번호 찾기\">\n");
      out.write("			</li>\n");
      out.write("			<li>주소</li>\n");
      out.write("			<li><input type=\"text\" name=\"addr\" id=\"addr\"></li>\n");
      out.write("			<li>상세주소</li>\n");
      out.write("			<li><input type=\"text\" name=\"detailaddr\" id=\"detailaddr\"></li>\n");
      out.write("			<li><input type=\"submit\" value=\"회원가입\"></li>\n");
      out.write("		</ul>\n");
      out.write("	</form>\n");
      out.write("</div>");
      out.write("\n");
      out.write("	<div class=\"bottomMenu\">\n");
      out.write("		@copyright Poby.\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
